- name: Install latest version of Docker dependencies
  become: yes
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    [
      "apt-transport-https",
      "ca-certificates",
      "curl",
      "gnupg-agent",
      "software-properties-common",
    ]

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get lsb_release codename needed for Docker repository
  shell: lsb_release -cs
  register: lsb_release_codename
  changed_when: False

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release_codename.stdout }} stable
    state: present

- name: Install docker-ce
  become: yes
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
